site_name: raster_bands
nav:
  - Home: index.md
  - API: autoapi/src/raster_bands

plugins:
  - search
  - mkdocs-autoapi:
      # autoapi_ignore:
      #   - tests/**/*
      autoapi_add_nav_entry: False
  - mkdocstrings